// Edit this file to update your profile. Leave unknown dates empty.
window.PROFILE = {
  name: 'Chengzhi Zhao',
  intro: 'Ph.D. Student · AI for Biology\nDepartment of Medical Systems Biology\nSchool of Basic Medical Sciences, Fudan University',
  about: 'I am a Ph.D. student in the Department of Medical Systems Biology at the School of Basic Medical Sciences, Fudan University. My research sits at the intersection of artificial intelligence and biomedicine, with a focus on single-cell and spatial omics, developmental biology, perturbation prediction, generative modeling, and biological foundation models.',
  signature: 'Understanding biology, one cell at a time.',
  links: [{ label: 'GitHub ↗', url: 'https://github.com/zczali4403' }],
  stops: [
    { city: 'Heze', photo: {"src": "assets/photos/heze.jpg", "alt": "Heze No. 1 High School entrance", "credit": "Heze No. 1 High School", "source": "https://www.hzyzh.com.cn/index.php/xinkegai", "x": "43%", "y": "0%"}, english: 'SHANDONG', province: 'Shandong', school: 'Heze No. 1 High School', stage: 'High School', years: '', title: 'Where the journey began', description: 'The first chapter of my academic journey, in Heze, Shandong.', coordinate: [115.48, 35.23], label: [20, -23] },
    { city: 'Chengdu', photo: {"src": "assets/photos/chengdu.jpg", "alt": "The Xipu south gate, inscribed with Tangshan Railway and Mining School", "credit": "Southwest Jiaotong University News", "source": "https://news.swjtu.edu.cn/info/1140/44255.htm", "x": "7%", "y": "46%"}, english: 'SICHUAN', province: 'Sichuan', school: 'Southwest Jiaotong University', stage: 'Undergraduate', years: '', title: 'An undergraduate chapter', description: 'Undergraduate studies at Southwest Jiaotong University in Chengdu.', coordinate: [104.07, 30.67], label: [16, -23] },
    { city: 'Shenzhen', photo: {"src": "assets/photos/shenzhen.png", "alt": "Southern University of Science and Technology entrance monument", "credit": "SUSTech College of Science", "source": "https://science.sustech.edu.cn/portal/article/index/id/156", "x": "37%", "y": "76%"}, english: 'GUANGDONG', province: 'Guangdong', school: 'Southern University of Science and Technology', stage: 'Graduate Studies', years: '', title: 'Exploring bioinformatics', description: 'Graduate studies in bioinformatics at Southern University of Science and Technology.', coordinate: [114.06, 22.54], label: [22, -12] },
    { city: 'Shanghai', photo: {"src": "assets/photos/shanghai.jpg", "alt": "Fudan University gate on the Handan campus", "credit": "Fudan University News", "source": "https://news.fudan.edu.cn/2023/0128/c45a133795/page.htm", "x": "78%", "y": "18%"}, english: 'SHANGHAI', province: 'Shanghai', school: 'Fudan University', stage: 'Ph.D. Student', years: '', title: 'At the intersection of AI and biology', description: 'Doctoral research in Medical Systems Biology, School of Basic Medical Sciences, Fudan University.', coordinate: [121.47, 31.23], label: [-25, 33] }
  ]
};
